In [ ]:
#importing
import numpy as np

Arrays

In [ ]:
#creating 1d array
a=np.array([1,2,3,4,5])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
#creating a 2D array
B=np.array([[2,3,4],[7,8,9]])
print(B)

[[2 3 4]
 [7 8 9]]


In [ ]:
#creating a 3D array rows,columns,groups
c=np.array([[[2,3,4],[6,7,8]],[[1,2,3],[1,3,4]]])
print(c)

[[[2 3 4]
  [6 7 8]]

 [[1 2 3]
  [1 3 4]]]


In [ ]:
D=np.ones((3,2))
print(D)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
d=np.zeros((3,2))
print(d)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
i=np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
c=np.eye(4,3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
d=np.ones((2,3,4,))
print(d)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
R=np.eye(4,3)
print(R)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
#arange
n=np.arange(3,31,3).reshape(5,2)
print(n)

[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]
 [27 30]]


In [ ]:
i=np.arange(5,1001,5).reshape(100,2)
print(i)

[[   5   10]
 [  15   20]
 [  25   30]
 [  35   40]
 [  45   50]
 [  55   60]
 [  65   70]
 [  75   80]
 [  85   90]
 [  95  100]
 [ 105  110]
 [ 115  120]
 [ 125  130]
 [ 135  140]
 [ 145  150]
 [ 155  160]
 [ 165  170]
 [ 175  180]
 [ 185  190]
 [ 195  200]
 [ 205  210]
 [ 215  220]
 [ 225  230]
 [ 235  240]
 [ 245  250]
 [ 255  260]
 [ 265  270]
 [ 275  280]
 [ 285  290]
 [ 295  300]
 [ 305  310]
 [ 315  320]
 [ 325  330]
 [ 335  340]
 [ 345  350]
 [ 355  360]
 [ 365  370]
 [ 375  380]
 [ 385  390]
 [ 395  400]
 [ 405  410]
 [ 415  420]
 [ 425  430]
 [ 435  440]
 [ 445  450]
 [ 455  460]
 [ 465  470]
 [ 475  480]
 [ 485  490]
 [ 495  500]
 [ 505  510]
 [ 515  520]
 [ 525  530]
 [ 535  540]
 [ 545  550]
 [ 555  560]
 [ 565  570]
 [ 575  580]
 [ 585  590]
 [ 595  600]
 [ 605  610]
 [ 615  620]
 [ 625  630]
 [ 635  640]
 [ 645  650]
 [ 655  660]
 [ 665  670]
 [ 675  680]
 [ 685  690]
 [ 695  700]
 [ 705  710]
 [ 715  720]
 [ 725  730]
 [ 735  740]
 [ 745  750]
 [ 755  760]
 [ 765  770]

In [ ]:
v=np.linspace(12,24,10)
print(v)

[12.         13.33333333 14.66666667 16.         17.33333333 18.66666667
 20.         21.33333333 22.66666667 24.        ]


In [ ]:
R=np.arange(9,15).reshape(2,3)
print(R)
L=np.arange(1,7).reshape(2,3)
print(L)
print(L+R)

[[ 9 10 11]
 [12 13 14]]
[[1 2 3]
 [4 5 6]]
[[10 12 14]
 [16 18 20]]


In [ ]:
G=np.sum((L,R),axis=1)
print(G)

[[ 5  7  9]
 [21 23 25]]


In [ ]:
h=np.ones((4,2))
g=np.ones((4,2))
print(np.sum((h,g),axis=0))
print(np.sum((h,g),axis=1))

[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]
[[4. 4.]
 [4. 4.]]


In [ ]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
print(A*B)
print(A@B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [ ]:
#b=np.array[25,289,361,81] #find square roots and iterarte through result values output 5 square is 25
b=[25,289,361,81]
for i in b:

  print(np.sqrt(i),"square is",i)

5.0 square is 25
17.0 square is 289
19.0 square is 361
9.0 square is 81
